#!/bin/bash
FILES='/home/kyle/glider_working/Sage_Data/sg573_processed/*.nc'
echo $FILES
for f in $FILES
do
	ncks -C -x -v sg_cal_vbd_min_cnts,\
sg_cal_vbd_max_cnts,\
sg_cal_vbd_cnts_per_cc,\
sg_cal_t_j,\
sg_cal_t_i,\
sg_cal_t_h,\
sg_cal_t_g,\
sg_cal_roll_min_cnts,\
sg_cal_roll_max_cnts,\
sg_cal_pump_rate_slope,\
sg_cal_pump_rate_intercept,\
sg_cal_pump_power_slope,\
sg_cal_pump_power_intercept,\
sg_cal_pitch_min_cnts,\
sg_cal_pitch_max_cnts,\
sg_cal_calibcomm_wetlabs,\
sg_cal_c_j,\
sg_cal_c_i,\
sg_cal_c_h,\
sg_cal_c_g,\
sg_cal_WETLabsCalData_Scatter880_wavelength,\
sg_cal_WETLabsCalData_Scatter880_scaleFactor,\
sg_cal_WETLabsCalData_Scatter880_resolution,\
sg_cal_WETLabsCalData_Scatter880_darkCounts,\
sg_cal_WETLabsCalData_Scatter470_wavelength,\
sg_cal_WETLabsCalData_Scatter470_scaleFactor,\
sg_cal_WETLabsCalData_Scatter470_resolution,\
sg_cal_WETLabsCalData_Scatter470_darkCounts,\
sg_cal_WETLabsCalData_Chlorophyll_scaleFactor,\
sg_cal_WETLabsCalData_Chlorophyll_resolution,\
sg_cal_WETLabsCalData_Chlorophyll_maxOutput,\
sg_cal_WETLabsCalData_Chlorophyll_darkCounts,\
sg_cal_WETLabsCalData_Chlorophyll_calTemperature,\
sg_cal_PAR_CalData_serialNumber,\
sg_cal_PAR_CalData_sensorDark,\
sg_cal_PAR_CalData_scalingFactor,\
sg_cal_PAR_CalData_manufacturer,\
sg_cal_PAR_CalData_calData,\
log__XMS_TOUTs,\
log__XMS_NAKs,\
log__SM_DEPTHo,\
log__SM_ANGLEo,\
log__CALLS,\
log_XPDR_VALID,\
log_XPDR_PINGS,\
log_XPDR_INHIBIT,\
log_XPDR_DEVICE,\
log_VBD_TIMEOUT,\
log_VBD_PUMP_AD_RATE_SURFACE,\
log_VBD_PUMP_AD_RATE_APOGEE,\
log_VBD_MIN,\
log_VBD_MAXERRORS,\
log_VBD_MAX,\
log_VBD_DBAND,\
log_VBD_CNV,\
log_VBD_BLEED_AD_RATE,\
log_USE_ICE,\
log_USE_BATHY,\
log_UPLOAD_DIVES_MAX,\
log_UNCOM_BLEED,\
log_T_WATCHDOG,\
log_T_TURN_SAMPINT,\
log_T_TURN,\
log_T_RSLEEP,\
log_T_NO_W,\
log_T_MISSION,\
log_T_LOITER,\
log_T_GPS_CHARGE,\
log_T_GPS_ALMANAC,\
log_T_GPS,\
log_T_DIVE,\
log_T_BOOST,\
log_T_ABORT,\
log_TGT_RADIUS,\
log_TGT_DEFAULT_LON,\
log_TGT_DEFAULT_LAT,\
log_TGT_AUTO_DEFAULT,\
log_TCM_TEMP,\
log_TCM_ROLL_OFFSET,\
log_TCM_PITCH_OFFSET,\
log_SURFACE_URGENCY_TRY,\
log_SURFACE_URGENCY_FORCE,\
log_SURFACE_URGENCY,\
log_STROBE,\
log_SPEED_FACTOR,\
log_SM_CC,\
log_SIM_W,\
log_SIM_PITCH,\
log_SEABIRD_T_J,\
log_SEABIRD_T_I,\
log_SEABIRD_T_H,\
log_SEABIRD_T_G,\
log_SEABIRD_C_J,\
log_SEABIRD_C_I,\
log_SEABIRD_C_H,\
log_SEABIRD_C_G,\
log_R_STBD_OVSHOOT,\
log_R_PORT_OVSHOOT,\
log_ROLL_TIMEOUT,\
log_ROLL_MIN,\
log_ROLL_MAXERRORS,\
log_ROLL_MAX,\
log_ROLL_DEG,\
log_ROLL_CNV,\
log_ROLL_AD_RATE,\
log_ROLL_ADJ_GAIN,\
log_ROLL_ADJ_DBAND,\
log_RELAUNCH,\
log_RAFOS_PEAK_OFFSET,\
log_RAFOS_HIT_WINDOW,\
log_RAFOS_DEVICE,\
log_RAFOS_CORR_THRESH,\
log_P_OVSHOOT,\
log_PRESSURE_YINT,\
log_PRESSURE_SLOPE,\
log_PITCH_VBD_SHIFT,\
log_PITCH_TIMEOUT,\
log_PITCH_MIN,\
log_PITCH_MAXERRORS,\
log_PITCH_MAX,\
log_PITCH_GAIN,\
log_PITCH_DBAND,\
log_PITCH_CNV,\
log_PITCH_AD_RATE,\
log_PITCH_ADJ_GAIN,\
log_PITCH_ADJ_DBAND,\
log_PHONE_SUPPLY,\
log_PHONE_DEVICE,\
log_N_NOSURFACE,\
log_N_NOCOMM,\
log_N_GPS,\
log_N_FILEKB,\
log_NAV_MODE,\
log_MOTHERBOARD,\
log_MISSION,\
log_MINV_24V,\
log_MINV_10V,\
log_MAX_BUOY,\
log_MASS,\
log_LOGGERS,\
log_LOGGERDEVICE4,\
log_LOGGERDEVICE3,\
log_LOGGERDEVICE2,\
log_LOGGERDEVICE1,\
log_KERMIT,\
log_KALMAN_USE,\
log_INT_PRESSURE_YINT,\
log_INT_PRESSURE_SLOPE,\
log_INTERNAL_PRESSURE,\
log_ID,\
log_ICE_FREEZE_MARGIN,\
log_HUMID,\
log_HEAPDBG,\
log_HEAD_ERRBAND,\
log_HEADING,\
log_GPS_DEVICE,\
log_GLIDE_SLOPE,\
log_FIX_MISSING_TIMEOUT,\
log_FILEMGR,\
log_FG_AHR_24Vo,\
log_FG_AHR_24V,\
log_FG_AHR_10Vo,\
log_FG_AHR_10V,\
log_FERRY_MAX,\
log_ESCAPE_HEADING_DELTA,\
log_ESCAPE_HEADING,\
log_D_TGT,\
log_D_SURF,\
log_D_SAFE,\
log_D_PITCH,\
log_D_OFFGRID,\
log_D_NO_BLEED,\
log_D_GRID,\
log_D_FLARE,\
log_D_FINISH,\
log_D_CALL,\
log_D_BOOST,\
log_D_ABORT,\
log_DIVE,\
log_DEVICE6,\
log_DEVICE5,\
log_DEVICE4,\
log_DEVICE3,\
log_DEVICE2,\
log_DEVICE1,\
log_DEEPGLIDERMB,\
log_DEEPGLIDER,\
log_C_VBD,\
log_C_ROLL_DIVE,\
log_C_ROLL_CLIMB,\
log_C_PITCH,\
log_COURSE_BIAS,\
log_COMPASS_USE,\
log_COMPASS_DEVICE,\
log_COMPASS2_DEVICE,\
log_COMM_SEQ,\
log_CF8_MAXERRORS,\
log_CAPUPLOAD,\
log_CAPMAXSIZE,\
log_CALL_WAIT,\
log_CALL_TRIES,\
log_CALL_NDIVES,\
log_APOGEE_PITCH,\
log_ALTIM_TOP_TURN_MARGIN,\
log_ALTIM_TOP_PING_RANGE,\
log_ALTIM_TOP_MIN_OBSTACLE,\
log_ALTIM_SENSITIVITY,\
log_ALTIM_PULSE,\
log_ALTIM_PING_DEPTH,\
log_ALTIM_PING_DELTA,\
log_ALTIM_FREQUENCY,\
log_ALTIM_BOTTOM_TURN_MARGIN,\
log_ALTIM_BOTTOM_PING_RANGE,\
log_AH0_24V,\
log_AH0_10V,\
log_AD7714Ch0Gain,\
log_TT8_MAMPS,\
log_TGT_NAME,\
log_TGT_LATLONG,\
log_SPEED_LIMITS,\
log_SM_GC,\
log_SM_CCo,\
log_SENSOR_SECS,\
log_SENSOR_MAMPS,\
log_SENSORS,\
log_MHEAD_RNG_PITCHd_Wd,\
log_MEM,\
log_KALMAN_Y,\
log_KALMAN_X,\
log_KALMAN_CONTROL,\
log_IRIDIUM_FIX,\
log_ERRORS,\
log_DEVICE_SECS,\
log_DEVICE_MAMPS,\
log_DEVICES,\
log_DATA_FILE_SIZE,\
log_CFSIZE,\
log_CAP_FILE_SIZE,\
log_24V_AH,\
log_10V_AH,\
eng_wlbb2flvmt_wl700ref,\
eng_wlbb2flvmt_wl700sig,\
eng_wlbb2flvmt_wl470sig,\
eng_wlbb2flvmt_wl470ref,\
eng_wlbb2flvmt_L2VMTtemp,\
eng_wlbb2flvmt_Chlsig,\
eng_wlbb2flvmt_Chlref,\
eng_vbdCC,\
eng_sbect_tempFreq,\
eng_sbect_condFreq,\
eng_sbe43_O2Freq,\
eng_rollCtl,\
eng_rollAng,\
eng_rec,\
eng_qsp_PARuV,\
eng_pitchCtl,\
eng_pitchAng,\
eng_head,\
eng_elaps_t_0000,\
eng_elaps_t,\
eng_depth,\
eng_GC_phase,\
wlbb2flvmt,\
vert_speed_gsm,\
vert_speed,\
start_of_climb_time,\
speed_qc,\
speed_gsm,\
speed,\
sg_cal_volmax,\
sg_cal_sbe_temp_freq_min,\
sg_cal_sbe_temp_freq_max,\
sg_cal_sbe_cond_freq_min,\
sg_cal_sbe_cond_freq_max,\
sg_cal_rho0,\
sg_cal_mission_title,\
sg_cal_mass,\
sg_cal_id_str,\
sg_cal_hd_c,\
sg_cal_ctcor,\
sg_cal_cpcor,\
sg_cal_calibcomm,\
sbe43,\
sbe41,\
reviewed,\
qsp2150,\
magnetic_variation,\
log_gps_time,\
log_gps_lon,\
log_gps_lat,\
log_HD_C,\
log_HD_B,\
log_HD_A,\
log_GPS2,\
log_GPS1,\
log_GPS,\
hdm_qc,\
glider,\
glide_angle_gsm,\
glide_angle,\
gc_vbd_secs,\
gc_vbd_retries,\
gc_vbd_i,\
gc_vbd_errors,\
gc_vbd_ctl,\
gc_vbd_ad,\
gc_st_secs,\
gc_roll_secs,\
gc_roll_retries,\
gc_roll_i,\
gc_roll_errors,\
gc_roll_ad,\
gc_pitch_secs,\
gc_pitch_retries,\
gc_pitch_i,\
gc_pitch_errors,\
gc_pitch_ctl,\
gc_pitch_ad,\
gc_ob_vertv,\
gc_gcphase,\
gc_end_secs,\
gc_depth,\
gc_data_pts,\
flight_avg_speed_north_gsm,\
flight_avg_speed_north,\
flight_avg_speed_east_gsm,\
flight_avg_speed_east,\
east_displacement_gsm,\
east_displacement,\
buoyancy,\
GPSE_qc,\
GPS2_qc,\
GPS1_qc,\
log_RHO,\
north_displacement,\
north_displacement_gsm,\
trajectory,\
horz_speed_gsm,\
horz_speed,\
depth_avg_curr_east_gsm,\
depth_avg_curr_north_gsm,\
CTD_qc,\
avg_latitude,\
latitude_gsm,\
longitude_gsm,\
ctd_time,\
ctd_pressure,\
ctd_depth,\
conductivity_raw,\
conductivity_raw_qc,\
salinity_raw,\
salinity_raw_qc,\
temperature_raw,\
temperature_raw_qc,\
aa4330,\
eng_aa4330_AirSat,\
eng_aa4330_CalPhase,\
eng_aa4330_O2,\
eng_aa4330_TCPhase,\
eng_aa4330_Temp,\
eng_wlbb2f_VFtemp,\
eng_wlbb2f_blueCount,\
eng_wlbb2f_blueRef,\
eng_wlbb2f_fluorCount,\
eng_wlbb2f_redCount,\
sg_cal_calibcomm_optode,\
sg_cal_comm_oxy_type,\
log_ALTIM_BOTTOM_PING,\
log_CURRENT,\
log_DIRECT_CONTROL,\
log_EBE_ENABLE,\
log_GC_LAST_COLLECTION,\
log_GC_WINDOW,\
log_LENGTH,\
log_ROLL_GAIN_P,\
log_T_BOOST_BLACKOUT,\
eng_wlbb2f_redRef,\
sg_cal_abs_compress,\
sg_cal_optode_FoilCoefA0,\
sg_cal_optode_FoilCoefA1,\
sg_cal_optode_FoilCoefA10,\
sg_cal_optode_FoilCoefA11,\
sg_cal_optode_FoilCoefA12,\
sg_cal_optode_FoilCoefA13,\
sg_cal_optode_FoilCoefA2,\
sg_cal_optode_FoilCoefA3,\
sg_cal_optode_FoilCoefA4,\
sg_cal_optode_FoilCoefA5,\
sg_cal_optode_FoilCoefA6,\
sg_cal_optode_FoilCoefA7,\
sg_cal_optode_FoilCoefA8,\
sg_cal_optode_FoilCoefA9,\
sg_cal_optode_FoilCoefB0,\
sg_cal_optode_FoilCoefB1,\
sg_cal_optode_FoilCoefB10,\
sg_cal_optode_FoilCoefB11,\
sg_cal_optode_FoilCoefB12,\
sg_cal_optode_FoilCoefB13,\
sg_cal_optode_FoilCoefB2,\
sg_cal_optode_FoilCoefB3,\
sg_cal_optode_FoilCoefB4,\
sg_cal_optode_FoilCoefB5,\
sg_cal_optode_FoilCoefB6,\
sg_cal_optode_FoilCoefB7,\
sg_cal_optode_FoilCoefB8,\
sg_cal_optode_FoilCoefB9,\
sg_cal_optode_PhaseCoef0,\
sg_cal_optode_PhaseCoef1,\
sg_cal_optode_PhaseCoef2,\
sg_cal_optode_PhaseCoef3,\
wlbb2f,\
aanderaa4330_dissolved_oxygen,\
aanderaa4330_dissolved_oxygen_qc,\
aanderaa4330_instrument_dissolved_oxygen,\
aanderaa4330_qc,\
aanderaa4330_results_time $f $f
	ncrename -d sg_data_point,time $f
	ncrename -d string_1,qc_info $f
done
